name: Merged notification

on:
  pull_request_target:
    types:
      - "closed"

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    if: github.repository == 'codinasion/codinasion' && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'harshraj8843'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: "Thanks very much for contributing! Your pull request has been merged 🎉 If you're looking for your next contribution, check out [our other open source projects](https://github.com/orgs/codinasion/repositories).
            })
